//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buildings()
        {
            this.Apartments = new HashSet<Apartments>();
        }
    
        public int building_id { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<System.DateTime> management_start_date { get; set; }
        public Nullable<int> floors { get; set; }
        public Nullable<int> apartments_count { get; set; }
        public Nullable<int> construction_year { get; set; }
        public Nullable<decimal> total_area { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartments> Apartments { get; set; }
    }
}
