//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debts
    {
        public int debt_id { get; set; }
        public int apartment_id { get; set; }
        public System.DateTime report_date { get; set; }
        public Nullable<decimal> water_debt { get; set; }
        public Nullable<decimal> electricity_debt { get; set; }
    
        public virtual Apartments Apartments { get; set; }
    }
}
