//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.ServiceRequests = new HashSet<ServiceRequests>();
        }
    
        public int employee_id { get; set; }
        public string full_name { get; set; }
        public string position { get; set; }
        public string phone_number { get; set; }
        public string login { get; set; }
        public string password_hash { get; set; }
        public Nullable<int> position_id { get; set; }
    
        public virtual Positions Positions { get; set; }
        public virtual Positions Positions1 { get; set; }
        public virtual Positions Positions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequests> ServiceRequests { get; set; }
    }
}
