//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PropertyManagementEntities : DbContext
    {
        public PropertyManagementEntities()
            : base("name=PropertyManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartments> Apartments { get; set; }
        public virtual DbSet<Buildings> Buildings { get; set; }
        public virtual DbSet<Debts> Debts { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Owners> Owners { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<PropertyOwnership> PropertyOwnership { get; set; }
        public virtual DbSet<ServiceRequests> ServiceRequests { get; set; }
    }
}
