//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int payment_id { get; set; }
        public int apartment_id { get; set; }
        public int period_month { get; set; }
        public int period_year { get; set; }
        public decimal amount_charged { get; set; }
        public Nullable<decimal> amount_paid { get; set; }
    
        public virtual Apartments Apartments { get; set; }
    }
}
