//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyOwnership
    {
        public int ownership_id { get; set; }
        public int owner_id { get; set; }
        public int apartment_id { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual Owners Owners { get; set; }
    }
}
