//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestExpenses
    {
        public int expense_id { get; set; }
        public int request_id { get; set; }
        public string expense_type { get; set; }
        public string description { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> expense_date { get; set; }
        public string created_by { get; set; }
    
        public virtual ServiceRequests ServiceRequests { get; set; }
    }
}
