//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHistory
    {
        public int history_id { get; set; }
        public int request_id { get; set; }
        public string status { get; set; }
        public string action { get; set; }
        public string description { get; set; }
        public Nullable<int> changed_by { get; set; }
        public System.DateTime changed_date { get; set; }
        public Nullable<int> employee_assigned { get; set; }
        public Nullable<int> estimated_duration { get; set; }
        public Nullable<int> actual_duration { get; set; }
        public string notes { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual ServiceRequests ServiceRequests { get; set; }
    }
}
