//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequests()
        {
            this.RequestExpenses = new HashSet<RequestExpenses>();
            this.RequestHistory = new HashSet<RequestHistory>();
        }
    
        public int request_id { get; set; }
        public int apartment_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string request_type { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<int> estimated_duration { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestExpenses> RequestExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestHistory> RequestHistory { get; set; }
    }
}
